"""empty message

Revision ID: 5d5683a58dad
Revises: 
Create Date: 2023-03-15 07:43:37.570226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5683a58dad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('no_rooms', sa.Integer(), nullable=True),
    sa.Column('no_bathrooms', sa.Integer(), nullable=True),
    sa.Column('price', sa.Double(), nullable=True),
    sa.Column('property_type', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
